-- Generated by Oracle SQL Developer Data Modeler Version: 2.0.0 Build: 584
--   at:        2012-10-16 15:15:16
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE AUTHORITY 
    ( 
     Id_Authority NUMBER (1)  NOT NULL , 
     Name_Of_Authority VARCHAR2 (10)  NOT NULL 
    ) 
;



ALTER TABLE AUTHORITY 
    ADD CONSTRAINT AUTHORITY_PK PRIMARY KEY ( Id_Authority ) ;


CREATE TABLE KIND_OF_RESOURCES 
    ( 
     Id_Kind NUMBER (5)  NOT NULL , 
     Name VARCHAR2 (10)  NOT NULL 
    ) 
;



ALTER TABLE KIND_OF_RESOURCES 
    ADD CONSTRAINT Rodzaje_Zasoby_PK PRIMARY KEY ( Id_Kind ) ;


CREATE TABLE LIBRARY 
    ( 
     Id_Library NUMBER (2)  NOT NULL , 
     Street VARCHAR2 (15)  NOT NULL , 
     Nr_House VARCHAR2 (4)  NOT NULL , 
     Nr_Local NUMBER (4)  NOT NULL , 
     Manager_Name VARCHAR2 (15)  NOT NULL , 
     Manager_Surname VARCHAR2 (20)  NOT NULL 
    ) 
;



ALTER TABLE LIBRARY 
    ADD CONSTRAINT LIBRARY_PK PRIMARY KEY ( Id_Library ) ;


CREATE TABLE RESOURCES 
    ( 
     Id_Resources NUMBER (5)  NOT NULL , 
     Id_Kind NUMBER (5)  NOT NULL , 
     Title VARCHAR2 (50)  NOT NULL , 
     Author_Name VARCHAR2 (15)  NOT NULL , 
     Author_Surname VARCHAR2 (30)  NOT NULL , 
     Is_Available CHAR (1)  NOT NULL , 
     Is_Reserve CHAR (1)  NOT NULL 
    ) 
;



ALTER TABLE RESOURCES 
    ADD CONSTRAINT ZASOBY_PK PRIMARY KEY ( Id_Resources ) ;


CREATE TABLE RESOURCES/LIBRARY 
    ( 
     Id_Resources NUMBER (5)  NOT NULL , 
     Id_Library NUMBER (2)  NOT NULL 
    ) 
;



ALTER TABLE RESOURCES/LIBRARY 
    ADD CONSTRAINT RESOURCES/LIBRARY_PK PRIMARY KEY ( Id_Resources, Id_Library ) ;


CREATE TABLE RESOURCES/USERS 
    ( 
     Id_Resources NUMBER (5)  NOT NULL , 
     Id_User NUMBER (6)  NOT NULL 
    ) 
;



ALTER TABLE RESOURCES/USERS 
    ADD CONSTRAINT RESOURCES/USERS_PK PRIMARY KEY ( Id_Resources, Id_User ) ;


CREATE TABLE USERS 
    ( 
     Id_User NUMBER (6)  NOT NULL , 
     Id_Authority NUMBER (1)  NOT NULL , 
     User_Name VARCHAR2 (15)  NOT NULL , 
     User_Surname VARCHAR2 (20)  NOT NULL , 
     Pesel NUMBER (11)  NOT NULL , 
     Limit NUMBER (1)  NOT NULL , 
     Amount_Of_Borrows NUMBER (1)  NOT NULL , 
     Login VARCHAR2 (15)  NOT NULL , 
     Password VARCHAR2 (10)  NOT NULL 
    ) 
;



ALTER TABLE USERS 
    ADD CONSTRAINT USERS_PK PRIMARY KEY ( Id_User ) ;



ALTER TABLE RESOURCES/LIBRARY 
    ADD CONSTRAINT RESOURCES/LIBRARY_LIBRARY_FK FOREIGN KEY 
    ( 
     Id_Library
    ) 
    REFERENCES LIBRARY 
    ( 
     Id_Library
    ) 
;


ALTER TABLE RESOURCES/LIBRARY 
    ADD CONSTRAINT RESOURCES/LIBRARY_RESOURCES_FK FOREIGN KEY 
    ( 
     Id_Resources
    ) 
    REFERENCES RESOURCES 
    ( 
     Id_Resources
    ) 
;


ALTER TABLE RESOURCES/USERS 
    ADD CONSTRAINT RESOURCES/USERS_RESOURCES_FK FOREIGN KEY 
    ( 
     Id_Resources
    ) 
    REFERENCES RESOURCES 
    ( 
     Id_Resources
    ) 
;


ALTER TABLE RESOURCES/USERS 
    ADD CONSTRAINT RESOURCES/USERS_USERS_FK FOREIGN KEY 
    ( 
     Id_User
    ) 
    REFERENCES USERS 
    ( 
     Id_User
    ) 
;


ALTER TABLE RESOURCES 
    ADD CONSTRAINT RESOURCES_KIND_OF_RESOURCES_FK FOREIGN KEY 
    ( 
     Id_Kind
    ) 
    REFERENCES KIND_OF_RESOURCES 
    ( 
     Id_Kind
    ) 
;


ALTER TABLE USERS 
    ADD CONSTRAINT USERS_AUTHORITY_FK FOREIGN KEY 
    ( 
     Id_Authority
    ) 
    REFERENCES AUTHORITY 
    ( 
     Id_Authority
    ) 
;


    
    
    
    
    
    
    

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- CREATE PROCEDURE                         0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE SNAPSHOT                          0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
